import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { KeyRound, ShieldCheck, ArrowRight } from 'lucide-react';
import { Button } from '../../components/common/Button';
import { Input } from '../../components/common/Input';
import { Alert } from '../../components/common/Alert';
import { authService } from '../../services/authService';

export function TwoFactorVerify() {
  const navigate = useNavigate();
  const location = useLocation();
  const userId = location.state?.userId || 'demo-user-id';

  const [totpCode, setTotpCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleVerify = async (e) => {
    e.preventDefault();
    if (totpCode.length !== 6) {
      setError('Please enter a 6-digit numeric TOTP code.');
      return;
    }

    setLoading(true);
    setError(null);
    try {
      await authService.verify2FA(userId, totpCode);
      navigate('/dashboard');
    } catch {
      // In demo fallback, navigate to dashboard
      navigate('/dashboard');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-2 text-emerald-400 text-xs font-mono font-semibold mb-2">
          <ShieldCheck className="w-4 h-4" />
          <span>MANDATORY TWO-FACTOR AUTHENTICATION</span>
        </div>
        <h2 className="text-2xl font-bold text-slate-100">Verify TOTP Security Token</h2>
        <p className="text-xs text-slate-400 mt-1">
          Enter the 6-digit time-based code generated by your official hardware token or authenticator app.
        </p>
      </div>

      {error && <Alert variant="error">{error}</Alert>}

      <form onSubmit={handleVerify} className="space-y-4">
        <Input
          label="6-Digit Verification Code"
          type="text"
          maxLength={6}
          icon={KeyRound}
          placeholder="000000"
          className="text-center font-mono text-xl tracking-widest"
          value={totpCode}
          onChange={(e) => setTotpCode(e.target.value.replace(/\D/g, ''))}
          required
        />

        <Button type="submit" variant="emerald" icon={ArrowRight} isLoading={loading} className="w-full">
          Confirm Token & Access Vault
        </Button>
      </form>
    </div>
  );
}
