/**
 * Cryptographic Audit Trail Action Types
 */
const AUDIT_ACTIONS = Object.freeze({
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_2FA_VERIFY: 'USER_2FA_VERIFY',
  
  CASE_CREATE: 'CASE_CREATE',
  CASE_UPDATE: 'CASE_UPDATE',
  CASE_STATUS_CHANGE: 'CASE_STATUS_CHANGE',
  CASE_OFFICER_ASSIGN: 'CASE_OFFICER_ASSIGN',

  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  DOCUMENT_DOWNLOAD: 'DOCUMENT_DOWNLOAD',
  DOCUMENT_VERIFY: 'DOCUMENT_VERIFY',
  DOCUMENT_TAMPER_FLAG: 'DOCUMENT_TAMPER_FLAG',
  DOCUMENT_NEW_VERSION: 'DOCUMENT_NEW_VERSION',

  OCR_EXTRACTION_SUCCESS: 'OCR_EXTRACTION_SUCCESS',
  OCR_EXTRACTION_FAILURE: 'OCR_EXTRACTION_FAILURE',

  SEMANTIC_SEARCH_QUERY: 'SEMANTIC_SEARCH_QUERY',
  PERMISSION_OVERRIDE: 'PERMISSION_OVERRIDE',
  SYSTEM_CONFIG_CHANGE: 'SYSTEM_CONFIG_CHANGE',
});

const ALL_AUDIT_ACTIONS = Object.freeze(Object.values(AUDIT_ACTIONS));

module.exports = {
  AUDIT_ACTIONS,
  ALL_AUDIT_ACTIONS,
};
