/**
 * Standard HTTP Status Codes and Domain-Specific Application Error Codes
 */
const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
});

const ERROR_CODES = Object.freeze({
  // Authentication & Session
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOTP_REQUIRED: 'TOTP_REQUIRED',
  INVALID_TOTP: 'INVALID_TOTP',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Case & Document Management
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DUPLICATE_CASE_NUMBER: 'DUPLICATE_CASE_NUMBER',
  INTEGRITY_CHECK_FAILED: 'INTEGRITY_CHECK_FAILED',
  TAMPER_DETECTED: 'TAMPER_DETECTED',
  HASH_MISMATCH: 'HASH_MISMATCH',

  // Storage & External APIs
  STORAGE_ERROR: 'STORAGE_ERROR',
  OCR_PROCESSING_FAILED: 'OCR_PROCESSING_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
});

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
};
